import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import "../globals.css";


import Sidebar from "../components/Sidebar";
import MobileSidebar from "../components/MobileSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#DFE0EB] `}>
        <Sidebar />
        <MobileSidebar />
        
        {children}
      </body>
    </html>
  );
}
